default:
  tags:
    - moodle

variables:
  MUSTACHE_IGNORE_NAMES: 'sortlist_entry.mustache'

stages:
  - preflight
  - test
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

include:
  - component: $CI_SERVER_FQDN/amc/moodle/moodle-ci/moodle-plugin-ci@5.0
  - component: $CI_SERVER_FQDN/amc/moodle/moodle-ci/moodle-devil-app@5.0
